sudo: required
services:
  - docker

before_install:
  - docker build -t abouchouar/docker-react -f Dockerfile.dev .

script:
  - docker run abouchouar/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-600089593469"
  bucket_path: "docker-react"  
  on:
    branch: master  
  access_key_id:
    secure: "AKIAYXOBAQZ6RKLC6JUG"
  secret_access_key:
    secure: "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"